#!/usr/bin/env python

from bs4 import BeautifulSoup

f=open('LUADprimaryfastq.xml','r')
fraw = f.read()
f.close()

fsoup = BeautifulSoup(fraw)

Anal_ID = []
for item in fsoup.find_all('analysis_id'):
	Anal_ID.append(item.string)

Participant_ID = []
for item in fsoup.findall('participant_id'):
	Participan_ID.append(item.string)

IDdict = dict(zip(Participant_ID,Anal_ID))

fout = open('LUADfastqAnalID.txt','w')
fout2 = open('LUADfastqParticipantID.txt','w')

for key in IDdict:
	fout2.write('%s\n' %(key))
	fout.write('%s\n' %(IDdict[key]))

fout.close()
fout2.close()
    